#ifndef __TYPES_H__
#define __TYPES_H__

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#define FACETRK_FORMAT_RGBA   0
#define FACETRK_FORMAT_YUVA   1
#define FACETRK_FORMAT_YUV    2
#ifndef FACETRK_FORMAT
#define FACETRK_FORMAT      FACETRK_FORMAT_YUV
#endif

#if   FACETRK_FORMAT == FACETRK_FORMAT_RGBA

#define FACETRK_GST_VIDEO_CAPS GST_VIDEO_CAPS_RGBA
#define HAARCOL_BYTESPIXEL    3

#elif FACETRK_FORMAT == FACETRK_FORMAT_YUVA

#define FACETRK_GST_VIDEO_CAPS GST_VIDEO_CAPS_YUV("YUVA")
#if USE_IPP
#define HAARCOL_BYTESPIXEL    4
#else
#define HAARCOL_BYTESPIXEL    3
#endif

#elif FACETRK_FORMAT == FACETRK_FORMAT_YUV

#define FACETRK_GST_VIDEO_CAPS GST_VIDEO_CAPS_YUV("YUV3")
#define HAARCOL_BYTESPIXEL    3

#endif

#endif //__TYPES_H__
